/*
 * M3 LoRA adapter parsing and validation (merge-on-load).
 *
 * Reads a musubi HiDream-O1 LoRA .safetensors, resolves every target against
 * the canonical map (config/hidream_lora_map_<profile>.json), validates
 * shapes/dtypes, and prepares the GPU merge. No forward-path changes.
 */

#include "hd_lora.h"
#include "safetensors.h"
#include "json.h"
#include "cuda_internal.h"
#include "o1_timing.h"

#include <math.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <cuda_runtime.h>

static char g_lora_error[512] = "";

static void lora_err(const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(g_lora_error, sizeof(g_lora_error), fmt, ap);
    va_end(ap);
}

const char *hd_lora_last_error(void) { return g_lora_error; }

/* ---- canonical map (generated by tools/lora/build_map.py) ---- */

typedef struct {
    const char *lora_prefix;
    const char *base_tensor;
    int out_dim;
    int in_dim;
} hd_lora_map_entry;

#include "lora_map_dev.inc"

static const hd_lora_map_entry *map_find(const char *prefix) {
    for (size_t i = 0; i < k_lora_map_dev_count; i++) {
        if (strcmp(k_lora_map_dev[i].lora_prefix, prefix) == 0)
            return &k_lora_map_dev[i];
    }
    return NULL;
}

/* ---- adapter parsing ---- */

typedef struct {
    hd_st_index idx;
    hd_lora_entry *entries;
    size_t n_entries;
    size_t cap_entries;
    char sha256[65];
} hd_lora_parse;

static int lora_entry_cmp(const void *a, const void *b) {
    const hd_lora_entry *x = a, *y = b;
    return strcmp(x->lora_prefix, y->lora_prefix);
}

/* Reads one tensor payload from the adapter file. */
static hd_status lora_read_tensor(const hd_st_index *idx, const char *name,
                                  void *dst) {
    const hd_st_tensor *t = hd_st_index_find(idx, name);
    if (!t) {
        lora_err("adapter missing tensor %s", name);
        return HD_ERR_MISSING;
    }
    return hd_st_read(idx->dir, t->shard, t->data_begin, t->nbytes, dst);
}

/* Converts adapter tensor bytes to FP32 host floats. Supports BF16/F16/F32. */
static hd_status lora_to_f32(const hd_st_tensor *t, const uint8_t *raw,
                             float **out) {
    int64_t n = t->numel;
    float *buf = malloc((size_t)n * sizeof(float));
    if (!buf) { lora_err("oom f32 staging"); return HD_ERR_OOM; }
    if (t->dtype == HD_DTYPE_F32) {
        memcpy(buf, raw, (size_t)n * 4);
    } else if (t->dtype == HD_DTYPE_BF16) {
        const uint16_t *p = (const uint16_t *)raw;
        for (int64_t i = 0; i < n; i++) {
            uint32_t bits = (uint32_t)p[i] << 16;
            memcpy(&buf[i], &bits, 4);
        }
    } else if (t->dtype == HD_DTYPE_F16) {
        const uint16_t *p = (const uint16_t *)raw;
        for (int64_t i = 0; i < n; i++) {
            uint32_t sign = (uint32_t)(p[i] >> 15) << 31;
            uint32_t exp = (p[i] >> 10) & 0x1f;
            uint32_t man = p[i] & 0x3ff;
            uint32_t bits;
            if (exp == 0) {
                if (man == 0) bits = sign;
                else {
                    exp = 127 - 15 + 1;
                    while (!(man & 0x400)) { man <<= 1; exp--; }
                    man &= 0x3ff;
                    bits = sign | (exp << 23) | (man << 13);
                }
            } else if (exp == 0x1f) {
                bits = sign | 0x7f800000u | (man << 13);
            } else {
                bits = sign | ((exp - 15 + 127) << 23) | (man << 13);
            }
            memcpy(&buf[i], &bits, 4);
        }
    } else {
        free(buf);
        lora_err("adapter tensor %s: unsupported dtype %d", t->name, (int)t->dtype);
        return HD_ERR_UNSUPPORTED;
    }
    *out = buf;
    return HD_OK;
}

/* ---- public API ---- */

hd_status hd_lora_apply(const hd_lora_config *cfg, hd_weight_store *store,
                        int device_id) {
    O1_TIMING_BEGIN("LORA_TOTAL");
    if (!cfg || cfg->count == 0) { O1_TIMING_END("LORA_TOTAL"); return HD_OK; }
    if (!store || !store->arena_ptr) {
        lora_err("lora: store not loaded");
        O1_TIMING_END("LORA_TOTAL");
        return HD_ERR_MISSING;
    }

    cudaError_t ce = cudaSetDevice(device_id);
    if (ce != cudaSuccess) { lora_err("cudaSetDevice: %s", cudaGetErrorString(ce)); return HD_ERR_IO; }

    /* ---- pass 1: parse + validate every adapter (no mutation) ---- */
    hd_lora_entry *all = NULL;
    size_t n_all = 0, cap_all = 0;

    for (size_t a = 0; a < cfg->count; a++) {
        const char *path = cfg->items[a].path;
        float mult = cfg->items[a].multiplier;
        if (!isfinite(mult)) { lora_err("lora %s: non-finite multiplier", path); return HD_ERR_PARSE; }

        O1_TIMING_BEGIN("LORA_PARSE");
        hd_st_index idx;
        hd_status st = hd_st_header_scan(path, &idx);
        if (st != HD_OK) { lora_err("lora %s: %s", path, hd_st_last_error()); return st; }

        /* Collect all module prefixes with up/down pairs. */
        for (int64_t i = 0; i < idx.n_tensors; i++) {
            const hd_st_tensor *t = &idx.tensors[i];
            const char *name = t->name;
            size_t nlen = strlen(name);
            const char *suffix = ".lora_down.weight";
            size_t slen = strlen(suffix);
            if (nlen > slen && strcmp(name + nlen - slen, suffix) == 0) {
                char prefix[256];
                size_t plen = nlen - slen;
                if (plen >= sizeof(prefix)) continue;
                memcpy(prefix, name, plen);
                prefix[plen] = '\0';

                /* up pair must exist */
                char up_key[512];
                snprintf(up_key, sizeof(up_key), "%s.lora_up.weight", prefix);
                if (!hd_st_index_find(&idx, up_key)) {
                    lora_err("lora %s: %s missing lora_up pair", path, prefix);
                    hd_st_index_free(&idx);
                    return HD_ERR_PARSE;
                }

                const hd_lora_map_entry *me = map_find(prefix);
                if (!me) {
                    lora_err("lora %s: target unknown for profile 'dev': %s", path, prefix);
                    hd_st_index_free(&idx);
                    return HD_ERR_UNSUPPORTED;
                }

                if (n_all == cap_all) {
                    size_t nc = cap_all ? cap_all * 2 : 64;
                    hd_lora_entry *ne = realloc(all, nc * sizeof(*ne));
                    if (!ne) { lora_err("oom lora entries"); hd_st_index_free(&idx); return HD_ERR_OOM; }
                    all = ne;
                    cap_all = nc;
                }
                hd_lora_entry *e = &all[n_all++];
                memset(e, 0, sizeof(*e));
                snprintf(e->lora_prefix, sizeof(e->lora_prefix), "%s", prefix);
                snprintf(e->base_tensor, sizeof(e->base_tensor), "%s", me->base_tensor);
                e->out_dim = me->out_dim;
                e->in_dim = me->in_dim;
                e->multiplier = mult;
            }
        }
        hd_st_index_free(&idx);
        O1_TIMING_END("LORA_PARSE");
    }

    if (n_all == 0) {
        lora_err("lora: no supported linear targets found");
        free(all);
        O1_TIMING_END("LORA_TOTAL");
        return HD_ERR_UNSUPPORTED;
    }

    /* ---- pass 2: read up/down/alpha, validate shapes, upload ---- */
    O1_TIMING_BEGIN("LORA_UPLOAD");
    for (size_t a = 0; a < cfg->count; a++) {
        const char *path = cfg->items[a].path;
        hd_st_index idx;
        hd_status st = hd_st_header_scan(path, &idx);
        if (st != HD_OK) { lora_err("lora %s: %s", path, hd_st_last_error()); free(all); return st; }

        for (size_t i = 0; i < n_all; i++) {
            hd_lora_entry *e = &all[i];
            if (e->down_dev) continue; /* already uploaded by an earlier adapter */

            char down_key[512], up_key[512], alpha_key[512];
            snprintf(down_key, sizeof(down_key), "%s.lora_down.weight", e->lora_prefix);
            snprintf(up_key, sizeof(up_key), "%s.lora_up.weight", e->lora_prefix);
            snprintf(alpha_key, sizeof(alpha_key), "%s.alpha", e->lora_prefix);

            const hd_st_tensor *dt = hd_st_index_find(&idx, down_key);
            const hd_st_tensor *ut = hd_st_index_find(&idx, up_key);
            if (!dt || !ut) continue; /* not in this adapter */

            if (dt->rank != 2 || ut->rank != 2) {
                lora_err("lora %s: %s non-linear", path, e->lora_prefix);
                hd_st_index_free(&idx); free(all);
                return HD_ERR_UNSUPPORTED;
            }
            int64_t rank = dt->shape[0];
            int64_t in_dim = dt->shape[1];
            int64_t out_dim = ut->shape[0];
            if (rank <= 0 || ut->shape[1] != rank) {
                lora_err("lora %s: %s rank mismatch", path, e->lora_prefix);
                hd_st_index_free(&idx); free(all);
                return HD_ERR_PARSE;
            }
            if (in_dim != e->in_dim || out_dim != e->out_dim) {
                lora_err("lora %s: %s shape mismatch base=[%d,%d] down=[%lld,%lld] up=[%lld,%lld]",
                         path, e->lora_prefix, e->out_dim, e->in_dim,
                         (long long)out_dim, (long long)in_dim,
                         (long long)out_dim, (long long)rank);
                hd_st_index_free(&idx); free(all);
                return HD_ERR_PARSE;
            }
            e->rank = (uint32_t)rank;

            /* alpha: scalar or default to rank */
            float alpha = (float)rank;
            const hd_st_tensor *at = hd_st_index_find(&idx, alpha_key);
            if (at) {
                if (at->numel != 1) {
                    lora_err("lora %s: %s malformed alpha", path, e->lora_prefix);
                    hd_st_index_free(&idx); free(all);
                    return HD_ERR_PARSE;
                }
                uint8_t raw[8];
                st = hd_st_read(idx.dir, at->shard, at->data_begin, at->nbytes, raw);
                if (st != HD_OK) { hd_st_index_free(&idx); free(all); return st; }
                if (at->dtype == HD_DTYPE_F32) memcpy(&alpha, raw, 4);
                else if (at->dtype == HD_DTYPE_BF16) {
                    uint32_t bits = (uint32_t)((const uint16_t *)raw)[0] << 16;
                    memcpy(&alpha, &bits, 4);
                } else if (at->dtype == HD_DTYPE_F16) {
                    uint32_t sign = (uint32_t)((const uint16_t *)raw)[0] >> 15 << 31;
                    uint32_t exp = (((const uint16_t *)raw)[0] >> 10) & 0x1f;
                    uint32_t man = ((const uint16_t *)raw)[0] & 0x3ff;
                    uint32_t bits;
                    if (exp == 0) {
                        if (man == 0) bits = sign;
                        else {
                            exp = 127 - 15 + 1;
                            while (!(man & 0x400)) { man <<= 1; exp--; }
                            man &= 0x3ff;
                            bits = sign | (exp << 23) | (man << 13);
                        }
                    } else if (exp == 0x1f) bits = sign | 0x7f800000u | (man << 13);
                    else bits = sign | ((exp - 15 + 127) << 23) | (man << 13);
                    memcpy(&alpha, &bits, 4);
                } else {
                    lora_err("lora %s: %s unsupported alpha dtype", path, e->lora_prefix);
                    hd_st_index_free(&idx); free(all);
                    return HD_ERR_UNSUPPORTED;
                }
                if (!isfinite(alpha) || alpha == 0.0f) {
                    lora_err("lora %s: %s invalid alpha %g", path, e->lora_prefix, alpha);
                    hd_st_index_free(&idx); free(all);
                    return HD_ERR_PARSE;
                }
            }
            e->alpha = alpha;

            /* read + convert to f32, upload */
            uint8_t *d_raw = malloc((size_t)dt->nbytes);
            uint8_t *u_raw = malloc((size_t)ut->nbytes);
            if (!d_raw || !u_raw) { free(d_raw); free(u_raw); hd_st_index_free(&idx); free(all); lora_err("oom raw"); return HD_ERR_OOM; }
            st = hd_st_read(idx.dir, dt->shard, dt->data_begin, dt->nbytes, d_raw);
            if (st == HD_OK) st = hd_st_read(idx.dir, ut->shard, ut->data_begin, ut->nbytes, u_raw);
            if (st != HD_OK) { free(d_raw); free(u_raw); hd_st_index_free(&idx); free(all); return st; }

            float *d_f32 = NULL, *u_f32 = NULL;
            st = lora_to_f32(dt, d_raw, &d_f32);
            if (st == HD_OK) st = lora_to_f32(ut, u_raw, &u_f32);
            free(d_raw); free(u_raw);
            if (st != HD_OK) { free(d_f32); free(u_f32); hd_st_index_free(&idx); free(all); return st; }

            ce = cudaMalloc(&e->down_dev, (size_t)rank * in_dim * 4);
            if (ce == cudaSuccess) ce = cudaMalloc(&e->up_dev, (size_t)out_dim * rank * 4);
            if (ce != cudaSuccess) {
                lora_err("lora %s: cudaMalloc: %s", path, cudaGetErrorString(ce));
                free(d_f32); free(u_f32); hd_st_index_free(&idx); free(all);
                return HD_ERR_OOM;
            }
            ce = cudaMemcpy(e->down_dev, d_f32, (size_t)rank * in_dim * 4, cudaMemcpyHostToDevice);
            if (ce == cudaSuccess) ce = cudaMemcpy(e->up_dev, u_f32, (size_t)out_dim * rank * 4, cudaMemcpyHostToDevice);
            free(d_f32); free(u_f32);
            if (ce != cudaSuccess) {
                lora_err("lora %s: cudaMemcpy: %s", path, cudaGetErrorString(ce));
                hd_st_index_free(&idx); free(all);
                return HD_ERR_IO;
            }

            /* bind base pointer from the resident arena */
            for (int64_t k = 0; k < store->n_allocs; k++) {
                if (strcmp(store->allocs[k].name, e->base_tensor) == 0) {
                    e->base_dev = store->allocs[k].dev_ptr;
                    break;
                }
            }
            if (!e->base_dev) {
                lora_err("lora %s: base tensor %s not found in store", path, e->base_tensor);
                hd_st_index_free(&idx); free(all);
                return HD_ERR_MISSING;
            }
        }
        hd_st_index_free(&idx);
    }
    O1_TIMING_END("LORA_UPLOAD");

    /* ---- pass 3: GPU merge ---- */
    O1_TIMING_BEGIN("LORA_MERGE");
    hd_status mst = hd_lora_merge_gpu(all, n_all, store->upload_stream);
    if (mst == HD_OK) {
        cudaError_t se = cudaStreamSynchronize(store->upload_stream);
        if (se != cudaSuccess) {
            lora_err("lora merge sync: %s", cudaGetErrorString(se));
            mst = HD_ERR_IO;
        }
    }
    O1_TIMING_END("LORA_MERGE");
    if (mst != HD_OK) {
        lora_err("lora merge failed: %s", hd_cuda_errbuf());
        for (size_t i = 0; i < n_all; i++) {
            if (all[i].down_dev) cudaFree(all[i].down_dev);
            if (all[i].up_dev) cudaFree(all[i].up_dev);
        }
        free(all);
        O1_TIMING_END("LORA_TOTAL");
        return mst;
    }

    /* ---- cleanup staging ---- */
    for (size_t i = 0; i < n_all; i++) {
        if (all[i].down_dev) cudaFree(all[i].down_dev);
        if (all[i].up_dev) cudaFree(all[i].up_dev);
    }
    free(all);
    O1_TIMING_END("LORA_TOTAL");
    return HD_OK;
}