import re, json, sys
sys.setrecursionlimit(10**6)
vocab = json.load(open("models/dev/vocab.json"))
merges_lines = open("models/dev/merges.txt").read().splitlines()
merges=[]
for line in merges_lines:
    line = line.replace("\ufeff","").rstrip("\n")
    if line=="": continue
    p=line.split(" ")
    if p and p[0].startswith("#"): continue
    if len(p)==2: merges.append((p[0],p[1]))
merges_rank={m:i for i,m in enumerate(merges)}

bs = list(range(0x21,0x7e+1))+list(range(0xa1,0xac+1))+list(range(0xae,0xff+1))
cs=bs[:]; n=0
for b in range(256):
    if b not in bs: bs.append(b); cs.append(256+n); n+=1
b2u={b:chr(c) for b,c in zip(bs,cs)}
u2b={c:b for b,c in b2u.items()}
PAT = re.compile(r"'s|'t|'re|'ve|'m|'ll|'d| ?[A-Za-z]+| ?[0-9]+| ?[^\sA-Za-z0-9]+|\s+(?!\S)|\s+")
at = json.load(open("models/dev/tokenizer_config.json"))["added_tokens_decoder"]
specials={d["content"]:int(k) for k,d in at.items() if d.get("special",False)}
# only the ones used by freeze pipeline matter, but include key vision/image too
template="<|im_start|>user\na red fox sits under a cherry blossom tree<|im_end|>\n<|im_start|>assistant\n"
expect=[151644,872,198,64,2518,38835,23011,1212,264,40880,88758,4916,151645,198,151644,77091,198]

candidate_pairs=set()   # all adjacent candidate pairs that exist in full merges
applied=set()
final_tokens=set()

def bpe_collect(parts):
    global candidate_pairs, applied
    while True:
        pairs={}
        for i in range(len(parts)-1):
            p=(parts[i],parts[i+1])
            if p in merges_rank:
                pairs[p]=merges_rank[p]
                candidate_pairs.add(p)
        if not pairs: break
        best=min(pairs,key=lambda p:pairs[p])
        applied.add(best)
        new=[]; j=0
        while j<len(parts):
            if j+1<len(parts) and (parts[j],parts[j+1])==best:
                new.append(parts[j]+parts[j+1]); j+=2
            else: new.append(parts[j]); j+=1
        parts=new
    for p in parts: final_tokens.add(p)
    return parts

def encode(text):
    ids=[]; i=0
    while i < len(text):
        matched=None
        for s in specials:
            if text.startswith(s,i):
                if matched is None or len(s)>len(matched[0]): matched=(s,specials[s])
        if matched:
            ids.append(matched[1]); i+=len(matched[0]); continue
        j=i
        while i < len(text) and not any(text.startswith(s,i) for s in specials): i+=1
        seg=text[j:i]
        for m in PAT.finditer(seg):
            w=seg[m.start():m.end()]
            bsbytes=w.encode("utf-8")
            pieces=[b2u[b] for b in bsbytes]
            wtoks=bpe_collect(pieces)
            ids.extend(vocab[t] for t in wtoks)
    return ids

got=encode(template)
assert got==expect, (got, expect)

# Build vocab subset
byte_pieces=[b2u[b] for b in range(256)]
# Need every piece string that is a candidate part (initial + merged) plus final tokens plus bytes
all_pieces=set(final_tokens)|set(byte_pieces)
# also all single merged intermediates from applied merges (they are left/right of applied)
for a,b in applied:
    all_pieces.add(a); all_pieces.add(b)
# Ensure each is in vocab
for p in all_pieces:
    assert p in vocab, ("missing vocab", repr(p))
# subset sorted by id
subset=sorted(((vocab[p],p) for p in all_pieces), key=lambda x:x[0])

# merge table = all candidate pairs sorted by rank, store left,right,rank
merges_list=sorted(candidate_pairs, key=lambda p: merges_rank[p])
assert all(p in merges_rank for p in merges_list)

def esc_c(s):
    # produce C string literal from python str (unicode domain) via utf-8
    b=s.encode("utf-8")
    out='"'
    for byte in b:
        if byte==0x22: out+='\\"'
        elif byte==0x5c: out+='\\\\'
        elif 0x20<=byte<0x7f: out+=chr(byte)
        else: out+='\\%03o'%byte
    out+='"'
    return out

lines=[]
lines.append('/* Generated by tools/_gen_c_tables.py from the frozen Qwen2Tokenizer')
lines.append('   (models/dev/vocab.json + merges.txt). DO NOT EDIT BY HAND. */')
lines.append('#ifndef HIDREAM_TOKENIZER_TABLES_H')
lines.append('#define HIDREAM_TOKENIZER_TABLES_H')
lines.append('')
lines.append('/* Byte -> BPE piece string (UTF-8), GPT-2 byte-to-unicode mapping. */')
lines.append('static const char *const hd_tok_byte_piece[256] = {')
for b in range(256):
    lines.append('    %s%s' % (esc_c(byte_pieces[b]), ',' if b<255 else ''))
lines.append('};')
lines.append('')
lines.append('/* Vocab subset: (id, piece string). Sorted by id. */')
lines.append('static const int hd_tok_vocab_id[%d] = {' % len(subset))
for i,(t,p) in enumerate(subset):
    lines.append('    %d%s' % (t, ',' if i<len(subset)-1 else ''))
lines.append('};')
lines.append('static const char *const hd_tok_vocab_str[%d] = {' % len(subset))
for i,(t,p) in enumerate(subset):
    lines.append('    %s%s' % (esc_c(p), ',' if i<len(subset)-1 else ''))
lines.append('};')
lines.append('')
lines.append('/* Merge table: left, right, rank. Sorted by rank (candidate merges for canonical path). */')
lines.append('static const int hd_tok_merge_count = %d;' % len(merges_list))
lines.append('static const char *const hd_tok_merge_left[%d] = {' % len(merges_list))
for i,(a,b) in enumerate(merges_list):
    lines.append('    %s%s' % (esc_c(a), ',' if i<len(merges_list)-1 else ''))
lines.append('};')
lines.append('static const char *const hd_tok_merge_right[%d] = {' % len(merges_list))
for i,(a,b) in enumerate(merges_list):
    lines.append('    %s%s' % (esc_c(b), ',' if i<len(merges_list)-1 else ''))
lines.append('};')
lines.append('static const int hd_tok_merge_rank[%d] = {' % len(merges_list))
for i,(a,b) in enumerate(merges_list):
    lines.append('    %d%s' % (merges_rank[(a,b)], ',' if i<len(merges_list)-1 else ''))
lines.append('};')
lines.append('')
lines.append('/* Special tokens (content, id). */')
spec_sel=['<|im_start|>','<|im_end|>','<|vision_start|>','<|vision_end|>','<|image_pad|>','<|video_pad|>']
lines.append('static const int hd_tok_special_count = %d;' % len(spec_sel))
lines.append('static const char *const hd_tok_special_str[%d] = {' % len(spec_sel))
for i,s in enumerate(spec_sel):
    lines.append('    %s%s' % (esc_c(s), ',' if i<len(spec_sel)-1 else ''))
lines.append('};')
lines.append('static const int hd_tok_special_id[%d] = {' % len(spec_sel))
for i,s in enumerate(spec_sel):
    lines.append('    %d%s' % (specials[s], ',' if i<len(spec_sel)-1 else ''))
lines.append('};')
lines.append('')
lines.append('#endif')
out='\n'.join(lines)+'\n'
open('src/model/tokenizer_tables.h','w').write(out)
print("bytes:",len(out),"vocab subset:",len(subset),"merges:",len(merges_list))
print("special ids:", {s:specials[s] for s in spec_sel})
print("GOT:",got)
print("MATCH:", got==expect)
