/*
 * test_torch_rng.c — bitwise gate for the torch-exact CPU RNG port.
 *
 * Verifies hd_torch_randn_f32 against golden bit patterns captured from
 * torch 2.12.1+cu130 (frozen oracle venv) for n = 1, 8, 15, 16, 17, 31,
 * 32, 1024 with seed 123457 (the M1 sanity seed+1).
 *
 * The golden files are generated by tools/gen_rng_golden.py and stored
 * under artifacts/m1/golden/M1_RNG/ as raw little-endian float32 bit
 * patterns (one u32 per line, hex).
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "torch_rng.h"

#define GOLDEN_DIR "artifacts/m1/golden/M1_RNG"

static const int kSizes[] = {1, 8, 15, 16, 17, 31, 32, 1024};
static const int kNumSizes = (int)(sizeof(kSizes) / sizeof(kSizes[0]));

static int load_golden(const char *path, uint32_t *out, int n) {
    FILE *f = fopen(path, "r");
    if (!f) {
        fprintf(stderr, "cannot open golden %s\n", path);
        return -1;
    }
    int got = 0;
    char line[64];
    while (got < n && fgets(line, sizeof(line), f)) {
        char *end = NULL;
        unsigned long v = strtoul(line, &end, 16);
        if (end == line) continue;
        out[got++] = (uint32_t)v;
    }
    fclose(f);
    return got == n ? 0 : -1;
}

int main(void) {
    int failures = 0;
    for (int s = 0; s < kNumSizes; s++) {
        int n = kSizes[s];
        char path[512];
        snprintf(path, sizeof(path), "%s/randn_n%d_seed123457.txt", GOLDEN_DIR, n);

        uint32_t *golden = (uint32_t *)malloc((size_t)n * sizeof(uint32_t));
        float *native = (float *)malloc((size_t)(n + 16) * sizeof(float));
        if (!golden || !native) {
            fprintf(stderr, "OOM\n");
            return 1;
        }
        if (load_golden(path, golden, n) != 0) {
            fprintf(stderr, "FAIL n=%d: golden missing (%s)\n", n, path);
            failures++;
            free(golden);
            free(native);
            continue;
        }

        hd_torch_rng rng;
        hd_torch_rng_seed(&rng, 123457);
        hd_torch_randn_f32(&rng, native, n);

        int bad = 0;
        for (int i = 0; i < n; i++) {
            uint32_t b;
            memcpy(&b, &native[i], 4);
            if (b != golden[i]) {
                if (bad < 4) {
                    fprintf(stderr, "  n=%d i=%d native=%08x golden=%08x\n", n, i, b, golden[i]);
                }
                bad++;
            }
        }
        if (bad == 0) {
            printf("PASS n=%d (bit-exact)\n", n);
        } else {
            printf("FAIL n=%d (%d/%d mismatched)\n", n, bad, n);
            failures++;
        }
        free(golden);
        free(native);
    }
    if (failures == 0) {
        printf("TORCH_RNG_GATE_OK\n");
        return 0;
    }
    printf("TORCH_RNG_GATE_FAIL (%d size(s) failed)\n", failures);
    return 1;
}